service: chainlink-hackathon-back
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: handler.handler
    timeout: 30
    events:
      - httpApi: '*'

plugins:
  - "serverless-offline"